// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltqhujliyocybuwcmadf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0cWh1amxpeW9jeWJ1d2NtYWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjYzMjcsImV4cCI6MjA2NzY0MjMyN30.eaqzmDJnLHErcbiZ7re1bzPL0ztYe28kyhENYA9ZHtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});